Repository goorm-dofarming/Frontend, pull requests merged in 2024-07, with the labels that each got.

#2 배포 빌드 수정
  .gitignore
  package.json
Labels: Chore

#3 chore: 프로젝트 환경 세팅 완료
  app/layout.tsx
  app/mocks/MSWComponent.tsx
  app/mocks/browser.ts
  app/mocks/handlers.ts
  app/mocks/index.ts
  app/mocks/server.ts
  app/utils/queryProvider.tsx
  package.json
  pnpm-lock.yaml
Labels: Chore

#5 [Docs] 배포
  .github/workflows/deploy.yaml
  app/mocks/MSWComponent.tsx
  package.json
  public/mockServiceWorker.js
Labels: Docs

#6 docs: ci/cd 테스트
  .github/workflows/deploy.yaml
Labels: Docs

#9 docs: github action 적용 완료
  app/page.tsx
Labels: Docs

#8 [Feat] 사이드바 (NavBar) 구현
  .gitmessage.txt
  app/_assets/icons/logo.png
  app/_assets/icons/logo.svg
  app/_components/Common/Input.tsx
  app/_components/main/Chat.tsx
  app/_components/main/Likes.tsx
  app/_components/main/Log.tsx
  app/_components/main/Map.tsx
  app/_components/main/NavBar/navbar.module.scss
  app/_components/main/NavBar/page.tsx
  app/_components/main/index.tsx
  app/_styles/constants/_color.scss
  app/_styles/constants/_index.scss
  app/_styles/index.scss
  app/_styles/mixins/_flexbox.scss
  app/_styles/mixins/_index.scss
  app/globals.css
  app/home.module.scss
  app/layout.tsx
  app/page.tsx
  package.json
  pnpm-lock.yaml
Labels: Feat

#10 [Feat]로그인, 회원가입 페이지 생성, 메인페이지 일부 생성
  app/_assets/main/N.svg
  app/_assets/main/chat.svg
  app/_assets/main/close.svg
  app/_assets/main/colored_Map.svg
  app/_assets/main/eye-closed.svg
  app/_assets/main/eye.svg
  app/_assets/main/g-logo.svg
  app/_assets/main/hearts.svg
  app/_assets/main/kakao.svg
  app/_assets/main/log.svg
  app/_assets/main/logo.svg
  app/_assets/main/modalClicked_Profile.svg
  app/_assets/main/settings.svg
  app/_assets/main/userProfile.svg
  app/_components/main/Modal.tsx
  app/_components/main/NavBar/navbar.module.scss
  app/_components/main/NavBar/page.tsx
  app/_components/main/modal/Login.tsx
  app/_components/main/modal/Signup.tsx
  app/_styles/common/commonColorStyles.ts
  app/_styles/keyframes.ts
  app/_styles/main/mainStyles.ts
  app/constatns/icons.ts
  app/globals.css
  app/page.tsx
  app/types/aboutMain.ts
  public/font/RedHatDisplay-Italic-VariableFont_wght.ttf
  public/font/RedHatDisplay-VariableFont_wght.ttf
Labels: Design, Feat

#11 [Feat] 로그인 회원가입 구현
  app/_components/Common/Modal.tsx
  app/_components/main/Main.tsx
  app/_components/main/Modal.tsx
  app/_components/main/modal/Login.tsx
  app/_components/main/modal/Signup.tsx
  app/_styles/common/commonColorStyles.ts
  app/_styles/common/modalStyles.ts
  app/_styles/main/buttons.ts
  app/_styles/main/inputs.ts
  app/_styles/main/mainStyles.ts
  app/hooks/Home/useToggle.tsx
  app/layout.tsx
  app/mocks/MSWComponent.tsx
  app/mocks/index.ts
  app/page.tsx
  app/registry.tsx
  app/types/aboutMain.ts
  next.config.mjs
  package.json
  pnpm-lock.yaml
Labels: Design, Feat, Refactor

#12 [Feat] 이메일 인증 기능 구현
  app/_components/main/Main.tsx
  app/_components/main/modal/Login.tsx
  app/_components/main/modal/Signup.tsx
  app/_styles/main/buttons.ts
  app/_styles/main/mainStyles.ts
  app/page.tsx
Labels: Design, Feat

#13 [Feat] 테마 설정 핀(랜덤핀), 카드 , 지도마커(랜덤핀사용예정)
  app/_assets/main/map/pin_activity.svg
  app/_assets/main/map/pin_cafe.svg
  app/_assets/main/map/pin_food.svg
  app/_assets/main/map/pin_mountain.svg
  app/_assets/main/map/pin_ocean.png
  app/_assets/main/map/pin_ocean.svg
  app/_assets/main/map/pin_random.svg
  app/_assets/main/map/pin_tour.svg
  app/_components/Common/Card.tsx
  app/_components/main/Map.tsx
  app/_components/main/Map/map.module.scss
  app/_components/main/Map/page.tsx
  app/_components/main/RandomPin/page.tsx
  app/_components/main/RandomPin/randomPin.module.scss
  app/_components/main/index.tsx
  app/_styles/mixins/_flexbox.scss
  app/favicon.ico
  app/home.module.scss
  app/layout.tsx
  app/mocks/handlers.ts
  app/page.tsx
  package.json
  pnpm-lock.yaml
  public/logo.svg
Labels: Feat

#14 [Feat] 채팅 공통 컴포넌트 구현
  app/_assets/icons/main_logo.png
  app/_components/main/Chat.tsx
  app/_components/main/NavBar/page.tsx
  app/_components/main/chat/chatList/ChatList.tsx
  app/_components/main/chat/chatList/EntireChatList.tsx
  app/_components/main/chat/chatList/MyChatList.tsx
  app/_components/main/chat/chatList/chatlist.module.scss
  app/_components/main/chat/chatSpace/ChatRoom.tsx
  app/_components/main/chat/chatSpace/ChatSpace.tsx
  app/_components/main/chat/chatSpace/chatspace.module.scss
  app/_components/main/chat/page.tsx
  app/_components/main/index.tsx
  app/_styles/common/commonColorStyles.ts
  app/_styles/constants/_color.scss
  app/_styles/main/chatStyles.ts
  app/api/chat/useGetEntireChats.ts
  app/api/chat/useGetMyChats.ts
  app/atom/stats.ts
  app/layout.tsx
  app/mocks/handlers.ts
  app/types/aboutChat.ts
  app/utils/recoilProvider.tsx
  package.json
  pnpm-lock.yaml
  public/region/경상남도.png
  public/region/부산광역시.png
  public/region/충청북도.png
Labels: Chore, Feat

#15 [Feat] 채팅방 생성 모달 구현, [Style] 모달 위치 및 배경 스타일링
  app/_components/Common/Modal.tsx
  app/_components/main/Main.tsx
  app/_components/main/chat/chatList/ChatList.tsx
  app/_components/main/chat/chatList/EntireChatList.tsx
  app/_components/main/chat/chatList/MyChatList.tsx
  app/_components/main/chat/chatList/chatlist.module.scss
  app/_components/main/chat/chatSpace/ChatSpace.tsx
  app/_components/main/modal/CreateChat.tsx
  app/_components/main/modal/createchat.module.scss
  app/_styles/common/modalStyles.ts
  app/_styles/constants/_color.scss
  app/_styles/main/buttons.ts
  app/_styles/main/mainStyles.ts
  app/atom/stats.ts
  app/mocks/handlers.ts
  app/page.tsx
  app/types/aboutChat.ts
Labels: Design, Feat

#16 [Feat] api, axios 클라이언트 생성 , interceptor 추가
  app/_config/index.ts
  app/api/apiClient.ts
  app/api/auth/index.ts
  app/api/basicClient.ts
  app/api/chat/index.ts
  app/api/user/index.ts
Labels: Feat

#17 [feat] 채팅방 생성 구현 및 서버 연결
  app/_components/main/chat/chatList/ChatList.tsx
  app/_components/main/chat/chatList/EntireChatList.tsx
  app/_components/main/chat/chatList/MyChatList.tsx
  app/_components/main/chat/chatList/chatlist.module.scss
  app/_components/main/chat/chatSpace/ChatSpace.tsx
  app/_components/main/chat/chatSpace/chatspace.module.scss
  app/_components/main/modal/CreateChat.tsx
  app/_components/main/modal/createchat.module.scss
  app/api/chat/useGetEntireChats.ts
  app/api/chat/useGetMyChats.ts
Labels: Feat

#18 [Feat] 랜덤핀수정, 맵 아이콘 추가, 메인화면 레이아웃 조정 및 맵 및 커스텀 마커 구현
  app/_assets/main/map/pin_location.png
  app/_assets/main/map/pin_location.svg
  app/_components/main/Main.tsx
  app/_components/main/Map/page.tsx
  app/_components/main/NavBar/navbar.module.scss
  app/_components/main/NavBar/page.tsx
  app/_components/main/RandomPin/page.tsx
  app/_components/main/RandomPin/randomPin.module.scss
  app/_styles/main/buttons.ts
  app/_styles/main/mainStyles.ts
  app/home.module.scss
  app/page.tsx
  package.json
  pnpm-lock.yaml
  tsconfig.json
Labels: Feat

#21 [Feat] 소셜 로그인 구현
  package.json
  pages/_app.tsx
  pages/api/callback.ts
  pages/login/kakaoLogin/index.tsx
  pages/login/naverLogin/index.tsx
  pnpm-lock.yaml
  src/_components/main/Main.tsx
  src/_components/main/modal/Login.tsx
  src/_components/main/modal/Signup.tsx
  src/hooks/Home/useGoogleLogin.tsx
  src/hooks/Home/useKaKaoLogin.tsx
  src/hooks/Home/useNaverLogin.tsx
Labels: Feat

#23 [Feat] 채팅방 검색 기능 구현, props 단순화
  pages/api/chat/index.ts
  src/_components/main/chat/chatList/ChatList.tsx
  src/_components/main/chat/chatList/EntireChatList.tsx
  src/_components/main/chat/chatList/MyChatList.tsx
  src/_components/main/chat/chatList/chatlist.module.scss
  src/_components/main/chat/chatSpace/chatspace.module.scss
  src/_components/main/chat/index.tsx
  src/_components/main/modal/chat/CreateChat.tsx
  src/_styles/main/chatStyles.ts
Labels: Feat, Refactor

#24 [Feat] 랜덤핀 기능 및 애니메이션, 커스텀 마커 추가
  pages/_app.tsx
  pages/api/map/index.ts
  pages/index.tsx
  public/favicon.ico
  src/_components/main/Main.tsx
  src/_components/main/Map/index.tsx
  src/_components/main/Map/map.module.scss
  src/_components/main/RandomPin/index.tsx
  src/_components/main/RandomPin/randomPin.module.scss
  src/_components/main/RandomPin/util.ts
  src/_styles/main/buttons.ts
  src/_styles/main/mainStyles.ts
  src/atom/stats.ts
  src/home.module.scss
  src/types/aboutMap.ts
Labels: Feat

#25 [Feat] 로그 페이지 생성
  package.json
  pages/_app.tsx
  pnpm-lock.yaml
  src/_assets/main/chat.svg
  src/_assets/main/hearts.svg
  src/_assets/main/log.svg
  src/_assets/main/log/log_img.svg
  src/_assets/main/settings.svg
  src/_components/Common/Card.tsx
  src/_components/Common/Modal.tsx
  src/_components/main/Log.tsx
  src/_components/main/Main.tsx
  src/_components/main/modal/Login.tsx
  src/_components/main/modal/Signup.tsx
  src/_styles/common/buttons.ts
  src/_styles/common/inputs.ts
  src/_styles/common/modalStyles.ts
  src/_styles/main/logStyles.ts
  src/_styles/main/mainStyles.ts
  src/constatns/icons.ts
  src/constatns/logExample.ts
  src/constatns/pinEamplet.ts
  src/mocks/handlers.ts
  src/types/aboutLog.ts
Labels: Feat

#27 [Feat] 채팅방 리스트 무한 스크롤 구현
  pages/api/chat/index.ts
  public/region/강원특별자치도.png
  public/region/경기도.png
  public/region/경상북도.png
  public/region/광주광역시.png
  public/region/대구광역시.png
  public/region/대전광역시.png
  public/region/서울특별시.png
  public/region/세종특별자치시.png
  public/region/울산광역시.png
  public/region/인천광역시.png
  public/region/전라남도.png
  public/region/전라북도.png
  public/region/제주특별자치도.png
  public/region/충청남도.png
  src/_components/main/chat/chatList/ChatList.tsx
  src/_components/main/chat/chatList/EntireChatList.tsx
  src/_components/main/chat/chatList/MyChatList.tsx
  src/_components/main/chat/chatList/chatlist.module.scss
  src/_components/main/chat/chatSpace/ChatSpace.tsx
  src/_components/main/chat/chatSpace/chatspace.module.scss
  src/_components/main/modal/chat/CreateChat.tsx
  src/atom/stats.ts
Labels: Feat, Refactor

#26 [Docs] HTTPS 적용
  .github/workflows/deploy.yml
  src/_components/main/Log.tsx
Labels: Docs

#28 docs: 2차 배포
  src/_components/main/chat/chatSpace/ChatSpace.tsx
  src/atom/stats.ts
  src/types/aboutMap.ts
Labels: Docs

#29 docs: 2차 배포
  .github/workflows/deploy.yml
Labels: Docs

#30 docs: 2차 배포
  deploy.sh
Labels: Docs

#33 [Fix] 검색 스크롤 수정, createdAt 변수 통일
  src/_components/main/chat/chatList/ChatList.tsx
  src/_components/main/chat/chatList/EntireChatList.tsx
  src/_components/main/chat/chatList/chatlist.module.scss
  src/_components/main/chat/chatSpace/ChatSpace.tsx
  src/_components/main/chat/index.tsx
  src/atom/stats.ts
  src/mocks/handlers.ts
  src/types/aboutChat.ts
Labels: Bugfix, Refactor

#34 [Hotfix] api 호출 수정
  .eslintrc.json
  pages/_app.tsx
  pages/api/auth/index.ts
  pages/api/callback.ts
  pages/login/kakaoLogin/index.tsx
  pages/login/naverLogin/index.tsx
  src/_components/main/Main.tsx
  src/_components/main/modal/Login.tsx
  src/_components/main/modal/Signup.tsx
Labels: Bugfix, Refactor

#35 [Feat] 랜덤핀/맵 구현, 커스텀 마커, 추천리스트 출력, 카드 수정
  next.config.mjs
  pages/api/map/index.ts
  pages/api/testClient.ts
  src/_components/Common/Card.tsx
  src/_components/main/Log.tsx
  src/_components/main/Main.tsx
  src/_components/main/Map/index.tsx
  src/_components/main/Map/map.module.scss
  src/_components/main/NavBar/index.tsx
  src/_components/main/RandomPin/index.tsx
  src/_components/main/RandomPin/util.ts
  src/_components/main/chat/chatSpace/ChatSpace.tsx
  src/_styles/main/logStyles.ts
  src/_styles/main/mainStyles.ts
  src/atom/stats.ts
  src/constatns/icons.ts
  src/types/aboutLog.ts
  src/types/aboutMap.ts
Labels: Feat

#36 fix: chat space type build error 수정
  src/_components/main/chat/chatSpace/ChatSpace.tsx
Labels: Feat

#37 [Feat] 프로필 드랍다운 수정
  pages/index.tsx
  src/_components/main/Main.tsx
  src/_components/main/Map/index.tsx
  src/_components/main/NavBar/index.tsx
  src/_components/main/ProfileDropdown/index.tsx
  src/_styles/main/mainStyles.ts
  src/atom/stats.ts
  src/constatns/icons.ts
Labels: Feat

#39 [Feat] 채팅 알림 SSE 서버 연결 및 알림 뱃지 구현
  package.json
  pages/index.tsx
  pnpm-lock.yaml
  src/_components/main/NavBar/index.tsx
  src/_components/main/NavBar/navbar.module.scss
  src/_components/main/ProfileDropdown/index.tsx
  src/_components/main/chat/chatList/ChatList.tsx
  src/_components/main/chat/chatSpace/ChatRoom.tsx
  src/_components/main/chat/chatSpace/ChatSpace.tsx
  src/_components/main/chat/index.tsx
  src/atom/stats.ts
Labels: Design, Feat, Refactor

#40 [Feat] 유저 프로필 수정 구현
  next.config.mjs
  pages/api/user/index.ts
  pages/index.tsx
  pages/login/kakaoLogin/index.tsx
  src/_assets/icons/hat_logo.png
  src/_components/Common/Landing.tsx
  src/_components/main/ProfileDropdown/index.tsx
  src/_components/main/chat/index.tsx
  src/_components/main/modal/EditUser.tsx
  src/_components/main/modal/Login.tsx
  src/_components/main/modal/edituser.module.scss
Labels: Design, Feat

#41 [fix] 유저 프로필 토글 수정
  src/_components/main/ProfileDropdown/index.tsx
Labels: Bugfix

#42 [Feat] 추천 API 적용 및 커스텀 오버레이 구현
  pages/_app.tsx
  pages/api/map/index.ts
  src/_components/Common/Card.tsx
  src/_components/main/Map/customOverlay.css
  src/_components/main/Map/index.tsx
  src/_components/main/Map/map.module.scss
  src/_components/main/RandomPin/index.tsx
  src/_components/main/RandomPin/randomPin.module.scss
  src/_components/main/RandomPin/util.ts
  src/_styles/common/commonColorStyles.ts
  src/types/aboutMap.ts
Labels: Feat

#43 [Feat] 로그 api 연결
  next.config.mjs
  pages/_app.tsx
  pages/api/log/index.ts
  pages/index.tsx
  src/_components/main/Log.tsx
  src/_components/main/Map/index.tsx
  src/_styles/main/logStyles.ts
  src/types/aboutLog.ts
Labels: Bugfix, Feat

#44 fix: 커스텀오버레이 구현 및 클릭이벤트 추가
  pages/index.tsx
  src/_assets/main/map/kakaotalk.png
  src/_assets/main/map/link.png
  src/_components/main/Map/customOverlay.css
  src/_components/main/Map/index.tsx
  src/_components/main/Map/utils.ts
  src/_components/main/RandomPin/index.tsx
  src/types/aboutMap.ts
Labels: Feat

#45 [Feat] 실시간 기반 채팅 알림, 메세지, 인원 등 업데이트 구현 / 채팅방 뷰 수정
  pages/api/chat/index.ts
  pages/api/user/index.ts
  pages/index.tsx
  src/_assets/main/defaultProfile.svg
  src/_components/Common/Landing.tsx
  src/_components/main/chat/chatList/ChatList.tsx
  src/_components/main/chat/chatList/EntireChatList.tsx
  src/_components/main/chat/chatList/MyChatList.tsx
  src/_components/main/chat/chatList/chatlist.module.scss
  src/_components/main/chat/chatSpace/ChatRoom.tsx
  src/_components/main/chat/chatSpace/ChatSpace.tsx
  src/_components/main/chat/chatSpace/chatspace.module.scss
  src/_components/main/chat/index.tsx
  src/_components/main/modal/chat/CreateChat.tsx
  src/_styles/common/commonColorStyles.ts
  src/atom/stats.ts
  src/types/aboutChat.ts
Labels: Bugfix, Design, Feat, Refactor

#46 [fix] build 에러 수정
  src/atom/stats.ts
Labels: Bugfix

#48 [Feat] Toast 컴포넌트 제작 및 적용, 로그아웃 구현
  pages/login/kakaoLogin/index.tsx
  pages/login/naverLogin/index.tsx
  src/_components/Common/Toast.tsx
  src/_components/main/NavBar/index.tsx
  src/_components/main/NavBar/navbar.module.scss
  src/_components/main/RandomPin/index.tsx
  src/_styles/common/commonColorStyles.ts
  src/_styles/common/toastStyles.ts
  src/_styles/kakaoLogin/kakaoLoginStyles.ts
  src/_styles/keyframes.ts
  src/home.module.scss
Labels: Design, Feat, Refactor

#49 [Feat] 로그 기능 구현
  .vscode/settings.json
  kakao.d.ts
  next.config.mjs
  src/_assets/icons/main_logo.jpg
  src/_components/main/Log.tsx
  src/_components/main/Map/index.tsx
  src/_components/main/log/cluster.ts
  src/_styles/common/commonColorStyles.ts
  src/_styles/main/logStyles.ts
  src/constatns/PinSort.ts
  src/types/aboutLog.ts
Labels: Bugfix, Design, Feat

#50 [Feat] 링크 공유 기능 구현, 추천 api 수정, map 수정, CardUI 수정 및 좋아요 UI 구현, recommend Type 속성 수정
  pages/api/kakaoClient.ts
  pages/api/map/index.ts
  pages/api/testClient.ts
  pages/tours/[id].tsx
  pages/tours/share.module.scss
  src/_assets/main/map/cloud.png
  src/_components/Common/Card.tsx
  src/_components/Common/CardListItem.tsx
  src/_components/main/Log.tsx
  src/_components/main/Map/index.tsx
  src/_components/main/Map/map.module.scss
  src/_components/main/Map/utils.ts
  src/_components/main/RandomPin/index.tsx
  src/_styles/constants/_color.scss
  src/atom/stats.ts
  src/types/aboutLog.ts
  src/types/aboutMap.ts
Labels: Feat

#51 [Fix] 전체적인 스타일 수정
  src/_assets/main/arrow.png
  src/_components/Common/Modal.tsx
  src/_components/main/Main.tsx
  src/_components/main/NavBar/index.tsx
  src/_components/main/NavBar/navbar.module.scss
  src/_components/main/RandomPin/index.tsx
  src/_components/main/RandomPin/randomPin.module.scss
  src/_components/main/modal/Login.tsx
  src/_components/main/modal/Signup.tsx
  src/_components/main/modal/chat/createchat.module.scss
  src/_components/main/modal/chat/smallmodal.module.scss
  src/_components/main/modal/edituser.module.scss
  src/_styles/common/buttons.ts
  src/_styles/common/modalStyles.ts
  src/_styles/main/mainStyles.ts
Labels: Bugfix, Design

#52 [Fix] colorTheme 수정
  src/_styles/common/commonColorStyles.ts
Labels: Bugfix

#53 feat: 로그쪽 수정 사항 반영
  pages/login/kakaoLogin/index.tsx
  pages/login/naverLogin/index.tsx
  src/_components/main/Log.tsx
  src/_components/main/Map/index.tsx
  src/_components/main/modal/Login.tsx
  src/atom/stats.ts
Labels: Bugfix, Design, Feat

#55 [Hotfix] cookie Hydration error 수정
  pages/index.tsx
  src/_components/main/Main.tsx
Labels: Hotfix

#56 [Feat] - 좋아요 기능 구현 , modai ui 수정, 버튼,input transition, input action 추가
  pages/api/chat/index.ts
  pages/api/map/index.ts
  pages/index.tsx
  pages/login/kakaoLogin/index.tsx
  pages/login/naverLogin/index.tsx
  pages/tours/[id].tsx
  src/_components/Common/Card.tsx
  src/_components/Common/Modal.tsx
  src/_components/main/Likes.tsx
  src/_components/main/Log.tsx
  src/_components/main/Map/index.tsx
  src/_components/main/NavBar/index.tsx
  src/_components/main/chat/index.tsx
  src/_components/main/modal/Login.tsx
  src/_components/main/modal/Signup.tsx
  src/_styles/common/buttons.ts
  src/_styles/common/inputs.ts
  src/_styles/common/modalStyles.ts
Labels: Feat
