Repository goorm-dofarming/Frontend, pull requests merged in 2024-08, with the labels that each got.

#57 [Feat] 가게 정보 및 리뷰 모달 구현
  src/_components/Common/Modal.tsx
  src/_components/main/Main.tsx
  src/_components/main/Map/index.tsx
  src/_components/main/modal/review/MakeReview.tsx
  src/_components/main/modal/review/PlaceInfo.tsx
  src/_components/main/modal/review/makereview.module.scss
  src/_components/main/modal/review/placeinfo.module.scss
  src/_styles/common/modalStyles.ts
  src/_styles/main/mainStyles.ts
Labels: Design, Feat

#60 [Fix] hydration error 수정
  src/_components/main/Main.tsx
Labels: Bugfix

#61 fix: hidration error, 다른 버그들
  src/_components/main/Log.tsx
  src/_components/main/ProfileDropdown/index.tsx
  src/_components/main/modal/Login.tsx
  src/_components/main/modal/Signup.tsx
  src/_styles/common/inputs.ts
Labels: Feat

#62 [Feat] 리뷰 생성 및 조회, 가게 정보 조회 기능 구현
  pages/api/review/index.ts
  src/_components/main/Map/index.tsx
  src/_components/main/chat/chatList/chatlist.module.scss
  src/_components/main/chat/chatSpace/ChatRoom.tsx
  src/_components/main/chat/chatSpace/chatspace.module.scss
  src/_components/main/modal/EditUser.tsx
  src/_components/main/modal/review/MakeReview.tsx
  src/_components/main/modal/review/PlaceInfo.tsx
  src/_components/main/modal/review/Star.tsx
  src/_components/main/modal/review/makereview.module.scss
  src/_components/main/modal/review/placeinfo.module.scss
  src/_styles/common/modalStyles.ts
  src/_styles/common/toastStyles.ts
  src/types/aboutReview.ts
Labels: Design, Feat

#63 [Fix] 좋아요 페이지 무한스크롤, 상태관리 에러 수정
  package.json
  pages/api/map/index.ts
  pages/index.tsx
  pages/tours/share.module.scss
  pnpm-lock.yaml
  src/_components/Common/Card.tsx
  src/_components/Common/Chip.tsx
  src/_components/main/Likes.tsx
  src/types/aboutLikes.ts
Labels: Bugfix

#64 [Fix] 링크 공유 에러
  src/_components/main/Map/index.tsx
Labels: Bugfix

#65 [Fix] user 타입 관련 에러 수정
  src/_components/main/modal/review/PlaceInfo.tsx
  src/_components/main/modal/review/placeinfo.module.scss
Labels: Bugfix

#66 [Feat] getLogData/share, fix:recommend Type
  pages/api/map/index.ts
  pages/tours/[id].tsx
  src/_components/main/Likes.tsx
  src/types/aboutLog.ts
  src/types/aboutMap.ts
Labels: Bugfix, Feat

#67 [Feat] 리뷰 수정 및 내 리뷰 확인 기능 구현, 리뷰 컴포넌트화
  pages/api/review/index.ts
  src/_components/main/Likes.tsx
  src/_components/main/Map/index.tsx
  src/_components/main/modal/review/MakeReview.tsx
  src/_components/main/modal/review/PlaceInfo.tsx
  src/_components/main/modal/review/ReviewComponent.tsx
  src/_components/main/modal/review/placeinfo.module.scss
  src/_styles/common/modalStyles.ts
  src/types/aboutReview.ts
Labels: Design, Feat

#68 [Fix] conflict 해결
  src/_components/main/Likes.tsx
Labels: Bugfix

#69 [Feat] 공유 기능만 구현
  kakao.d.ts
  scripts/deploy.sh
  src/_components/Common/Card.tsx
  src/_components/main/Likes.tsx
  src/_components/main/Log.tsx
  src/_components/main/Map/index.tsx
  src/_components/main/Map/utils.ts
  src/_components/main/modal/Login.tsx
  src/_styles/main/logStyles.ts
Labels: Bugfix, Feat

#70 feat: 로그 타입 오류 수정
  src/_components/main/Log.tsx
Labels: Bugfix

#71 [Feat] 리뷰 삭제 및 리뷰별 좋아요 기능 구현
  pages/api/review/index.ts
  src/_components/main/Log.tsx
  src/_components/main/modal/chat/EnterChat.tsx
  src/_components/main/modal/chat/LeaveChat.tsx
  src/_components/main/modal/review/MakeReview.tsx
  src/_components/main/modal/review/PlaceInfo.tsx
  src/_components/main/modal/review/component/DeleteReview.tsx
  src/_components/main/modal/review/component/ReviewComponent.tsx
  src/_components/main/modal/review/component/Star.tsx
  src/_components/main/modal/review/placeinfo.module.scss
  src/_components/main/modal/smallmodal.module.scss
  src/types/aboutReview.ts
Labels: Design, Feat, Refactor

#72 [Feat] 리뷰 무한 스크롤
  src/_components/main/modal/review/PlaceInfo.tsx
  src/_components/main/modal/review/placeinfo.module.scss
Labels: Design, Feat

#73 [Feat] 카드에 별점 추가 , UI 및 애니메이션 수정, 버그 수정
  pages/index.tsx
  pages/login/kakaoLogin/index.tsx
  src/_components/Common/Card.tsx
  src/_components/Common/Chip.tsx
  src/_components/main/Likes.tsx
  src/_components/main/Log.tsx
  src/_components/main/Main.tsx
  src/_components/main/Map/index.tsx
  src/_components/main/NavBar/index.tsx
  src/_components/main/ProfileDropdown/index.tsx
  src/_components/main/RandomPin/index.tsx
  src/_components/main/RandomPin/randomPin.module.scss
  src/_components/main/chat/chatSpace/ChatSpace.tsx
  src/_styles/common/buttons.ts
  src/_styles/main/mainStyles.ts
  src/constatns/icons.ts
  src/home.module.scss
Labels: Bugfix

#74 [Fix] 토큰문제 해결
  pages/api/apiClient.ts
  pages/login/kakaoLogin/index.tsx
  pages/login/naverLogin/index.tsx
  src/_components/main/Log.tsx
  src/_components/main/Map/index.tsx
  src/_components/main/ProfileDropdown/index.tsx
  src/_components/main/modal/Login.tsx
Labels: Bugfix

#75 [Fix] 채팅 및 리뷰 줄바꿈 설정
  pages/api/apiClient.ts
  src/_components/main/Log.tsx
  src/_components/main/chat/chatSpace/ChatRoom.tsx
  src/_components/main/chat/chatSpace/chatspace.module.scss
  src/_components/main/modal/review/PlaceInfo.tsx
  src/_components/main/modal/review/component/ReviewComponent.tsx
Labels: Bugfix, Design

#76 [Fix] map, ui
  src/_components/main/Log.tsx
  src/_components/main/Map/index.tsx
  src/_components/main/modal/edituser.module.scss
Labels: Design

#77 [Fix] ui
  pages/globals.css
  src/_components/Common/Modal.tsx
  src/_components/main/RandomPin/randomPin.module.scss
  src/_components/main/modal/EditUser.tsx
  src/_components/main/modal/Login.tsx
  src/_components/main/modal/Signup.tsx
  src/_styles/common/buttons.ts
  src/_styles/common/modalStyles.ts
  src/home.module.scss
Labels: Design

#79 [Fix] 전체적인 CSS 수정
  src/_components/Common/Card.tsx
  src/_components/Common/Dropdown.tsx
  src/_components/main/Likes.tsx
  src/_components/main/Log.tsx
  src/_components/main/Map/index.tsx
  src/_components/main/Map/map.module.scss
  src/_components/main/Map/utils.ts
  src/_components/main/ProfileDropdown/index.tsx
  src/home.module.scss
Labels: Design

#78 [Fix] marker cluster에러 수정
  src/_components/main/Log.tsx
  src/_components/main/Map/index.tsx
Labels: Bugfix

#81 [Fix] 로그 스크롤바 포커스로 이동
  src/_components/main/Log.tsx
  src/_styles/main/logStyles.ts
Labels: Feat

#82 [Fix] pin, cluster
  kakao.d.ts
  src/_components/main/Log.tsx
  src/_components/main/Map/index.tsx
  src/_components/main/RandomPin/index.tsx
  src/_styles/main/logStyles.ts
Labels: Bugfix

#83 [Style] 채팅 랜딩 이미지 변경
  src/_components/main/chat/chatSpace/ChatSpace.tsx
Labels: Design

#84 [Feat] logpage- 카드눌렀을때 화면이동
  src/_components/main/Log.tsx
  src/_components/main/Map/index.tsx
  src/_styles/main/logStyles.ts
Labels: Feat

#85 [Feat] 채팅 리스트 refetch 시간 설정
  src/_components/main/chat/chatList/EntireChatList.tsx
  src/_components/main/chat/index.tsx
Labels: Feat

#86 [Fix] like UI, 토스트 추가, 드랍다운, 애니메이션 수정, 태그 오류수정
  src/_components/Common/Dropdown.tsx
  src/_components/main/Likes.tsx
  src/_components/main/Main.tsx
  src/_components/main/RandomPin/randomPin.module.scss
  src/_components/main/modal/chat/CreateChat.tsx
  src/_components/main/modal/chat/createchat.module.scss
  src/_styles/common/toastStyles.ts
  src/_styles/main/mainStyles.ts
  src/types/aboutLikes.ts
Labels: Bugfix

#87 [Fix] 전체 채팅 무한 로딩 해결
  pages/tours/[id].tsx
  src/_components/Common/Chip.tsx
  src/_components/Common/Dropdown.tsx
  src/_components/main/Likes.tsx
  src/_components/main/Log.tsx
  src/_components/main/Map/utils.ts
  src/_components/main/NavBar/index.tsx
  src/_components/main/ProfileDropdown/index.tsx
  src/_components/main/RandomPin/index.tsx
  src/_components/main/chat/chatList/EntireChatList.tsx
  src/_components/main/chat/chatList/MyChatList.tsx
  src/_components/main/chat/index.tsx
  src/_components/main/modal/review/MakeReview.tsx
  src/_components/main/modal/review/PlaceInfo.tsx
Labels: Bugfix, Refactor

#88 [Fix] StyledComponent, Image Warning 해결
  src/_components/Common/Card.tsx
  src/_components/Common/Chip.tsx
  src/_components/Common/Dropdown.tsx
  src/_components/Common/Landing.tsx
  src/_components/Common/Modal.tsx
  src/_components/Common/Toast.tsx
  src/_components/main/Main.tsx
  src/_components/main/ProfileDropdown/index.tsx
  src/_components/main/modal/Login.tsx
  src/_components/main/modal/Signup.tsx
  src/_components/main/modal/review/component/Star.tsx
  src/_styles/common/inputs.ts
  src/_styles/common/modalStyles.ts
  src/_styles/common/toastStyles.ts
  src/_styles/main/mainStyles.ts
Labels: Bugfix

#89 feat: 소셜 로그인 리다이렉션 수정
  .gitignore
  .vscode/settings.json
  appspec.yml
  pages/index.tsx
  scripts/deploy.sh
  src/_components/main/modal/Login.tsx
Labels: Bugfix, Chore

#90 [Feat] 이미지 확대 모달 구현
  pages/index.tsx
  src/_components/main/modal/review/component/ReviewComponent.tsx
  src/_components/main/modal/review/modal/imageModal.tsx
  src/_components/main/modal/review/modal/imagemodal.module.scss
Labels: Feat, Refactor

#91 [feat] 공유 링크 내 스크롤바 삭제
  pages/tours/share.module.scss
  src/_components/Common/CardListItem.tsx
Labels: Design

#92 [feat] 모달 외부 클릭시 모달 닫기
  src/_components/Common/Modal.tsx
  src/_components/main/modal/review/modal/imageModal.tsx
  src/_components/main/modal/review/modal/imagemodal.module.scss
Labels: Feat

#93 [Fix] 채팅방 생성 및 입장 시 해당 채팅방 포커스, 장소 정보 모달 뜨는 시간 조정
  src/_components/Common/Dropdown.tsx
  src/_components/main/Likes.tsx
  src/_components/main/Log.tsx
  src/_components/main/Map/index.tsx
  src/_components/main/chat/chatList/ChatList.tsx
  src/_components/main/chat/chatList/EntireChatList.tsx
Labels: Bugfix, Feat

#95 [Fix] 배포 후 발견된 에러 수정
  pages/index.tsx
  src/_components/Common/Card.tsx
  src/_components/main/Map/utils.ts
  src/_components/main/chat/chatList/EntireChatList.tsx
  src/_components/main/chat/chatList/MyChatList.tsx
  src/_components/main/chat/chatSpace/ChatSpace.tsx
  src/_components/main/modal/review/PlaceInfo.tsx
Labels: Bugfix, Refactor

#96 [Fix] 채팅 에러 수정
  pages/api/chat/index.ts
  src/_components/main/chat/chatList/ChatList.tsx
  src/_components/main/chat/chatList/EntireChatList.tsx
  src/_components/main/chat/chatList/MyChatList.tsx
  src/_components/main/modal/review/PlaceInfo.tsx
Labels: Bugfix, Refactor

#97 [Feat] 유저 정보 이메일 추가
  pages/index.tsx
  src/_components/Common/Card.tsx
  src/_components/main/Log.tsx
  src/_components/main/ProfileDropdown/index.tsx
  src/_components/main/modal/EditUser.tsx
Labels: Refactor

#98 [Fix] 배포 후 오류들 수정
  pages/index.tsx
  src/_components/Common/Card.tsx
  src/_components/main/Likes.tsx
  src/_components/main/Map/index.tsx
  src/_components/main/chat/chatSpace/ChatRoom.tsx
  src/_components/main/chat/chatSpace/ChatSpace.tsx
  src/_components/main/chat/index.tsx
  src/_components/main/modal/review/PlaceInfo.tsx
  src/_components/main/modal/review/placeinfo.module.scss
  src/_styles/main/mainStyles.ts
  src/types/aboutLog.ts
  src/types/aboutMap.ts
Labels: Bugfix

#99 fix: 채팅방 인원수 에러 해결
  src/_components/main/chat/chatList/EntireChatList.tsx
  src/_components/main/chat/chatSpace/ChatSpace.tsx
Labels: Bugfix
